apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: snapshot-test
  namespace: default
spec:
  snapshotClassName: default-snapclass
  source:
    name: pvc-disk
    kind: PersistentVolumeClaim